// Datos de ejemplo para el MVP
export const sampleExperiences = [
  {
    name: "Ecoturismo Lacandón",
    description: "Explora la selva lacandona con guías locales de la comunidad maya. Descubre la rica biodiversidad de uno de los ecosistemas más importantes de México, hogar de jaguares, monos aulladores y cientos de especies de aves. La experiencia incluye caminatas por senderos ancestrales, visitas a cascadas escondidas y la oportunidad de conocer las tradiciones y cosmovisión del pueblo lacandón.",
    shortDescription: "Aventura en la selva lacandona con guías mayas locales",
    state: "Chiapas",
    municipality: "Ocosingo",
    community: "Lacanjá Chansayab",
    latitude: "16.7500",
    longitude: "-91.1167",
    category: "ecoturismo" as const,
    imageUrl: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=800",
    contactEmail: "ecoturismo.lacandon@ejemplo.com",
    contactPhone: "+52 919 123 4567",
    isFeatured: true,
  },
  {
    name: "Avistamiento de Ballenas en Baja",
    description: "Vive la experiencia única de observar ballenas grises en su santuario natural. Las comunidades pesqueras de Baja California Sur te llevan en lanchas tradicionales para un encuentro cercano con estos majestuosos mamíferos marinos durante su temporada de reproducción. Una experiencia de conservación marina que beneficia directamente a las familias locales.",
    shortDescription: "Observación de ballenas grises con pescadores locales",
    state: "Baja California Sur",
    municipality: "Mulegé",
    community: "San Ignacio",
    latitude: "27.2833",
    longitude: "-112.8667",
    category: "observacion_naturaleza" as const,
    imageUrl: "https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=800",
    contactEmail: "ballenas.sanignacio@ejemplo.com",
    contactPhone: "+52 615 234 5678",
    isFeatured: true,
  },
  {
    name: "Ruta del Mezcal Artesanal",
    description: "Conoce el proceso tradicional de elaboración del mezcal en los valles de Oaxaca. Visita palenques familiares donde generaciones de maestros mezcaleros han perfeccionado este arte ancestral. Aprende sobre las diferentes variedades de agave, participa en la cosecha y degusta mezcales únicos mientras apoyas la economía local.",
    shortDescription: "Experiencia gastronómica y cultural del mezcal oaxaqueño",
    state: "Oaxaca",
    municipality: "Santiago Matatlán",
    community: "San Dionisio Ocotepec",
    latitude: "16.8667",
    longitude: "-96.3833",
    category: "gastronomia" as const,
    imageUrl: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=800",
    contactEmail: "mezcal.artesanal@ejemplo.com",
    contactPhone: "+52 951 345 6789",
    isFeatured: true,
  },
  {
    name: "Senderismo en la Sierra Gorda",
    description: "Recorre los senderos de la Reserva de la Biosfera Sierra Gorda, una de las áreas naturales protegidas más diversas de México. Guías comunitarios te llevarán por bosques de niebla, cascadas y cañones mientras conoces proyectos de conservación liderados por las comunidades locales.",
    shortDescription: "Caminatas guiadas en la Reserva de la Biosfera",
    state: "Querétaro",
    municipality: "Jalpan de Serra",
    community: "Cuatro Palos",
    latitude: "21.2167",
    longitude: "-99.4667",
    category: "turismo_aventura" as const,
    imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800",
    contactEmail: "sierragorda.eco@ejemplo.com",
    contactPhone: "+52 441 456 7890",
    isFeatured: false,
  },
  {
    name: "Turismo Rural en la Huasteca",
    description: "Sumérgete en la vida cotidiana de las comunidades teenek y náhuatl de la Huasteca Potosina. Participa en actividades agrícolas tradicionales, aprende a preparar zacahuil y otras delicias locales, y disfruta de las impresionantes cascadas y pozas de agua turquesa de la región.",
    shortDescription: "Inmersión cultural en comunidades indígenas de la Huasteca",
    state: "San Luis Potosí",
    municipality: "Aquismón",
    community: "Tanchachín",
    latitude: "21.6167",
    longitude: "-99.0167",
    category: "turismo_rural" as const,
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    contactEmail: "huasteca.rural@ejemplo.com",
    contactPhone: "+52 489 567 8901",
    isFeatured: false,
  },
  {
    name: "Observación de Aves en Yucatán",
    description: "Descubre la increíble diversidad de aves de la Península de Yucatán con guías especializados de las comunidades mayas. Desde flamencos rosados hasta tucanes y motmots, esta experiencia te lleva por manglares, cenotes y selvas para avistar más de 200 especies de aves.",
    shortDescription: "Avistamiento de aves con guías mayas especializados",
    state: "Yucatán",
    municipality: "Celestún",
    community: "Reserva de Celestún",
    latitude: "20.8667",
    longitude: "-90.4000",
    category: "observacion_naturaleza" as const,
    imageUrl: "https://images.unsplash.com/photo-1480044965905-02098d419e96?w=800",
    contactEmail: "aves.yucatan@ejemplo.com",
    contactPhone: "+52 999 678 9012",
    isFeatured: true,
  },
  {
    name: "Artesanías Textiles de Oaxaca",
    description: "Aprende las técnicas ancestrales de tejido en telar de cintura con maestras artesanas zapotecas. Conoce el proceso completo desde el hilado del algodón y la tintura con pigmentos naturales hasta la creación de piezas únicas. Una experiencia que preserva tradiciones milenarias.",
    shortDescription: "Taller de tejido tradicional con artesanas zapotecas",
    state: "Oaxaca",
    municipality: "Teotitlán del Valle",
    community: "Teotitlán del Valle",
    latitude: "17.0333",
    longitude: "-96.5167",
    category: "turismo_cultural" as const,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
    contactEmail: "textiles.zapotecas@ejemplo.com",
    contactPhone: "+52 951 789 0123",
    isFeatured: false,
  },
  {
    name: "Kayak en Manglares de Sian Ka'an",
    description: "Navega en kayak por los canales de la Reserva de la Biosfera Sian Ka'an, Patrimonio de la Humanidad. Guías de las comunidades mayas costeras te llevarán por este ecosistema único donde conviven manglares, arrecifes y selva, hogar de manatíes, cocodrilos y delfines.",
    shortDescription: "Aventura en kayak por la Reserva Sian Ka'an",
    state: "Quintana Roo",
    municipality: "Felipe Carrillo Puerto",
    community: "Punta Allen",
    latitude: "19.7833",
    longitude: "-87.4667",
    category: "turismo_aventura" as const,
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    contactEmail: "siankaan.kayak@ejemplo.com",
    contactPhone: "+52 984 890 1234",
    isFeatured: false,
  },
];

export const sampleResources = [
  {
    title: "Guía de Buenas Prácticas en Turismo Comunitario",
    description: "Manual completo con lineamientos para implementar prácticas sostenibles en proyectos de turismo comunitario. Incluye casos de éxito y herramientas prácticas.",
    type: "guia" as const,
    category: "Turismo Comunitario",
    author: "SECTUR",
    isPublic: true,
  },
  {
    title: "Manual de Conservación de Biodiversidad para Prestadores",
    description: "Documento técnico que explica cómo integrar criterios de conservación en las actividades turísticas comunitarias.",
    type: "manual" as const,
    category: "Conservación de Biodiversidad",
    author: "CONANP",
    isPublic: true,
  },
  {
    title: "Infografía: Ecosistemas de México",
    description: "Material visual que presenta los principales ecosistemas de México y su importancia para el turismo sostenible.",
    type: "infografia" as const,
    category: "Conservación de Biodiversidad",
    author: "SEMARNAT",
    isPublic: true,
  },
  {
    title: "Normativa del Turismo de Naturaleza en México",
    description: "Compilación de las principales normas y regulaciones aplicables al turismo de naturaleza y comunitario.",
    type: "normativa" as const,
    category: "Normatividad",
    author: "SECTUR",
    isPublic: true,
  },
  {
    title: "Guía de Comercialización para Empresas Comunitarias",
    description: "Estrategias y herramientas para promocionar y comercializar experiencias de turismo comunitario.",
    type: "guia" as const,
    category: "Comercialización",
    author: "FONATUR",
    isPublic: true,
  },
];

export const sampleCourses = [
  {
    title: "Introducción al Turismo Comunitario Sostenible",
    description: "Curso básico que presenta los fundamentos del turismo comunitario, sus beneficios y principios de sostenibilidad. Ideal para comunidades que inician su proyecto turístico.",
    shortDescription: "Fundamentos del turismo comunitario para principiantes",
    category: "Turismo Comunitario",
    duration: "8 horas",
    level: "basico" as const,
    isFeatured: true,
  },
  {
    title: "Conservación de Biodiversidad y Turismo",
    description: "Aprende a integrar criterios de conservación en tu oferta turística. Incluye identificación de especies, manejo de áreas naturales y educación ambiental.",
    shortDescription: "Integra la conservación en tu proyecto turístico",
    category: "Conservación de Biodiversidad",
    duration: "12 horas",
    level: "intermedio" as const,
    isFeatured: true,
  },
  {
    title: "Gestión Empresarial para Cooperativas Turísticas",
    description: "Herramientas de administración, contabilidad y organización para empresas comunitarias de turismo.",
    shortDescription: "Administración y finanzas para cooperativas",
    category: "Gestión Empresarial",
    duration: "16 horas",
    level: "intermedio" as const,
    isFeatured: false,
  },
  {
    title: "Marketing Digital para Turismo Comunitario",
    description: "Estrategias de promoción en redes sociales, creación de contenido y posicionamiento en línea para experiencias turísticas.",
    shortDescription: "Promociona tu experiencia en medios digitales",
    category: "Marketing Digital",
    duration: "10 horas",
    level: "basico" as const,
    isFeatured: true,
  },
  {
    title: "Guía de Naturaleza Certificado",
    description: "Programa avanzado de formación para guías especializados en interpretación ambiental y observación de fauna.",
    shortDescription: "Certificación para guías de naturaleza",
    category: "Conservación de Biodiversidad",
    duration: "40 horas",
    level: "avanzado" as const,
    isFeatured: false,
  },
];

export const sampleBadges = [
  {
    name: "Distintivo Semilla",
    description: "Reconocimiento inicial para prestadores de servicios turísticos comunitarios que demuestran compromiso con la sostenibilidad y han completado la capacitación básica.",
    level: "semilla" as const,
    requirements: "Registro completo, documentación verificada, capacitación introductoria, compromiso de sostenibilidad firmado",
    isActive: true,
  },
  {
    name: "Distintivo Excelencia",
    description: "Máximo reconocimiento para prestadores que demuestran excelencia en turismo comunitario sostenible con prácticas verificadas de conservación e impacto comunitario documentado.",
    level: "excelencia" as const,
    requirements: "Distintivo Semilla vigente, evaluación de sostenibilidad aprobada, certificaciones avanzadas, prácticas de conservación verificadas, impacto comunitario documentado",
    isActive: true,
  },
];
